fix: break down invite sent/failed method
session-foundation/libsession-util-nodejs pull request #4
Opened 2024-11-28 05:45 UTC by Bilb

2024-11-29 05:38 UTC, yougotwill requested changes

2024-11-29 05:38 UTC, yougotwill commented on types/groups/groupmembers.d.ts
> +    memberSetInviteFailed: (pubkeyHex: PubkeyType) => void;
I think you have swapped these. I think this should be `memberSetInviteSent` and the one below should be `memberSetInviteFailed` ?

2024-12-02 02:33 UTC, Bilb commented on types/groups/groupmembers.d.ts
> +    memberSetInviteFailed: (pubkeyHex: PubkeyType) => void;
updated

2024-12-02 04:36 UTC, yougotwill approved these changes
LGTM 🚢

2024-12-02 04:37 UTC, yougotwill approved these changes

2024-12-02 04:40 UTC, merged